name: base
channels:
  - pythonocc
  - conda-forge
dependencies:
  - pythonocc-core=7.5.1
  - pythreejs=2.2.1
  - ifcopenshell
  - python-graphviz
  - shapely
  - ipycanvas
  - lxml
  - sidecar
  - ipycytoscape
  - networkx
  - nbgitpuller
