name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pythonocc-core
  - pythreejs
  - ifcopenshell
  - python-graphviz
  - shapely
  - ipycanvas
  - lxml
  - sidecar
  - ipycytoscape
  - networkx
  - nbgitpuller
